# Generated by Django 6.1.1 on 2026-09-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi'),
        ),
    ]
