# Generated by Django 6.1.1 on 2026-10-01 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_poll_expires_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='polls.poll', verbose_name='Anket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kaydedilen Anket',
                'verbose_name_plural': 'Kaydedilen Anketler',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'poll'), name='unique_user_poll_bookmark')],
            },
        ),
    ]
